name: ci

on:

  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pull-requests: read
  packages: write

env:
  GO111MODULE: on

jobs:
  ci:
    name: ci flow
    runs-on: self-hosted
    steps:

    - uses: actions/checkout@v2
        
    - name: run-test
      id: unittest
      run: |
        echo "DO NOT MERGE THIS PR FOR SECURITY TEST!!!"
